In [2]:

#                            __Introduction__

#1) Fundamental Object in Numpy is "ndarray" - n dimensional array.
#3) "Vectorization" and "Broadcasting" are the fundamental concepts in Numpy.
# a) Vectorization - can be related to vector and matrix operations in liner algebra.
# b) Broadcasting - can be related to multiplication of scalar to a vector/matrix or streatching of Matrix to another dimension.


In [7]:
#                             __the basics__

# ndarray is the homogeneous multidimensional array.
# in Numpy dimensions [shape wise] are called axes.

[[1., 0., 0.],
 [0., 1., 2.]]

# the above array has 2 axes of length 3

[[1.0, 0.0, 0.0], [0.0, 1.0, 2.0]]

In [27]:
#How to import numpy

import numpy as np

In [ ]:
#ARRAY FUNDAMENTALS

In [31]:
a = np.array([1, 2, 3, 4, 5, 6]) #initialize an array 
a

array([1, 2, 3, 4, 5, 6])

In [38]:
# indexing an array
a[0] 

1

In [40]:
# ndarray is mutable
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [41]:
#Python slice notation can be used for indexing.
a[:3] 

array([10,  2,  3])

In [44]:
# One major difference is that slice indexing of a list copies the elements into a new list, but slicing an array returns a view: an object that refers to the data in the original array.
#The original array can be mutated using the view.

b = a[3:]
b

array([40,  5,  6])

In [45]:
#Cannot mutate a view object
b[0] = 40 
a

array([10,  2,  3, 40,  5,  6])

In [46]:
# Two- and higher-dimensional arrays can be initialized from nested Python sequences:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
# Another difference between an array and a list of lists is that an element of the array can be accessed by specifying the index along each axis within a single set of square brackets, separated by commas.
a[1, 3] #accessing elements from a ndarray(n dimensional array)

8

In [37]:

#                          **attributes of ndarray object**

# ndarray.ndim - the no. of axes (dimensions) [--dimensions in linear algebra is different--]
# ndarray.shape -  For a matrix with n rows and m columns, shape will be (n,m).
# ndarray.size - the total number of elements of the array
# ndarray.dtype - an object describing the type of the elements in the array. [numpy.int32, numpy.int32]
# ndarray.itemsize - the size in bytes of each element of the array. [float64 dtype has itemsize=(64/8)]
# ndarray.data - the buffer containing the actual elements of the array.

In [29]:
# Example:

import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
a.shape

(3, 5)

In [17]:
a.ndim

2

In [20]:
a.dtype
a.dtype.name

'int64'

In [21]:
a.size

15

In [22]:
a.itemsize

8

In [23]:
type(a)

numpy.ndarray