In [4]:
###-- Basic array operation --###

#This section covers addition, subtraction, multiplication, division, and more

#Eg:
import numpy as np
data = np.array([1,2])
ones = np.ones(2, dtype=int)
data + ones #Addition

array([2, 3])

In [6]:
data - ones #Subtraction

array([0, 1])

In [10]:
data*data #Multiplicaton

array([1, 2])

In [9]:
data/data #Divide

array([1., 1.])

In [12]:
# find sum() of elements in an array
a = np.array([1,2,3,4])
a.sum()

10

In [15]:
# To add the rows or the columns in a 2D array, you would specify the axis.

b = np.array([[1,1],
              [2,2]])
b.sum(axis=0) # sum on y axis

array([3, 3])

In [17]:
b.sum(axis=1) # sum on x axis

array([2, 4])

In [18]:
###-- Broadcasting --###

In [20]:
data = np.array([1,2])
data * 1.6

array([1.6, 3.2])

In [21]:
###-- More Array Operations --###

#This section covers maximum, minimum, sum, mean, product, standard deviation, and more

In [23]:
data.max() # max

2

In [24]:
data.min() # min

1

In [25]:
data.sum() # sum

3

In [27]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],  #Eg 2
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
c = [a.max(), a.min(), a.sum()]
c

[0.82485143, 0.05093587, 4.8595784]

In [29]:
a.min(axis=0) # min in col vector

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [30]:
###-- Creating Matrices --###

In [31]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
# indexing and slicing matrix
data[0,1]

2

In [36]:
data[1:3] # slicing the rows

array([[3, 4],
       [5, 6]])

In [40]:
data[0:2,0] # slicing the col

array([1, 3])

In [43]:
#agg vectors
agg_vectors = [data.min(), data.max(), data.sum()]
agg_vectors

[1, 6, 21]

In [45]:
#agg vectors axis/dimension wise
data = np.array([[1, 2], [5, 3], [4, 6]])
av = [data,data.max(axis=0), data.max(axis=1)]
av

[array([[1, 2],
        [5, 3],
        [4, 6]]),
 array([5, 6]),
 array([2, 5, 6])]

In [46]:
# add and multiply matrices

data = np.array([[1, 2],
                 [3, 4]])
ones = np.array([[1, 1], 
                 [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [48]:
# **You can do these arithmetic operations on matrices of different sizes, but only if one matrix has only one column or one row.**
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [49]:
###-- Generating random numbers --###

In [54]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.integers(5, size=(2,4)) #array of 2X4 filled with random numbers

array([[3, 0, 4, 4],
       [1, 2, 2, 3]])

In [55]:
###-- How to Get unique items and Counts --###

In [57]:
#Example:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_vals = np.unique(a)
print(unique_vals)


[11 12 13 14 15 16 17 18 19 20]


In [59]:
unique_vals, indices_list = np.unique(a, return_index=True) # To also get index of unique vals
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [60]:
unique_values, occurrence_count = np.unique(a, return_counts=True) # to get the frequency count of unique values 
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [61]:
#Same with 2D array
# Example
a_2d = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 10, 11, 12], 
                 [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [62]:
unique_rows = np.unique(a_2d, axis=0) #unique elements/Arrays along axis/dimensions
print(unique_rows) # this gives unique rows

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [70]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_index=True, return_counts=True )
print(indices) # Gives row index of unique rows

[0 1 2]


In [72]:
print(occurrence_count) # Gives no. of times each row occurs

[2 1 1]


In [73]:
###-- Transposing and reshaping a matrix --###

In [74]:
data = np.array([[1,2],
                 [3,4],
                 [5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
data.reshape(2,3) # Reshaping a Matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [79]:
arr.transpose() # Transpose Matrix

array([[0, 3],
       [1, 4],
       [2, 5]])

In [80]:
arr.T # Transpose Matrix

array([[0, 3],
       [1, 4],
       [2, 5]])

In [81]:
###-- How to reverse an array --###

In [86]:
#eg:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr) #use *np.flip()* to reverse the array
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [ ]:
# Reshaping and flattening multidimensional arrays

In [6]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
# When you use "flatten", changes to your new array won’t change the parent array.
#Example:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [11]:
# But when you use "ravel", the changes you make to the new array will affect the parent array.
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
