In [2]:
###-- Basic array operation --###

#This section covers addition, subtraction, multiplication, division, and more

#Eg:
import numpy as np
data = np.array([1,2])
ones = np.ones(2, dtype=int)
data + ones #Addition

array([2, 3])

In [6]:
data - ones #Subtraction

array([0, 1])

In [10]:
data*data #Multiplicaton

array([1, 2])

In [9]:
data/data #Divide

array([1., 1.])

In [12]:
# find sum() of elements in an array
a = np.array([1,2,3,4])
a.sum()

10

In [15]:
# To add the rows or the columns in a 2D array, you would specify the axis.

b = np.array([[1,1],
              [2,2]])
b.sum(axis=0) # sum on y axis

array([3, 3])

In [17]:
b.sum(axis=1) # sum on x axis

array([2, 4])

In [18]:
###-- Broadcasting --###

In [20]:
data = np.array([1,2])
data * 1.6

array([1.6, 3.2])

In [21]:
###-- More Array Operations --###

#This section covers maximum, minimum, sum, mean, product, standard deviation, and more

In [23]:
data.max() # max

2

In [24]:
data.min() # min

1

In [25]:
data.sum() # sum

3

In [27]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],  #Eg 2
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
c = [a.max(), a.min(), a.sum()]
c

[0.82485143, 0.05093587, 4.8595784]

In [29]:
a.min(axis=0) # min in col vector

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [30]:
###-- Creating Matrices --###

In [31]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
# indexing and slicing matrix
data[0,1]

2

In [36]:
data[1:3] # slicing the rows

array([[3, 4],
       [5, 6]])

In [40]:
data[0:2,0] # slicing the col

array([1, 3])

In [43]:
#agg vectors
agg_vectors = [data.min(), data.max(), data.sum()]
agg_vectors

[1, 6, 21]

In [45]:
#agg vectors axis/dimension wise
data = np.array([[1, 2], [5, 3], [4, 6]])
av = [data,data.max(axis=0), data.max(axis=1)]
av

[array([[1, 2],
        [5, 3],
        [4, 6]]),
 array([5, 6]),
 array([2, 5, 6])]

In [46]:
# add and multiply matrices

data = np.array([[1, 2],
                 [3, 4]])
ones = np.array([[1, 1], 
                 [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [48]:
# **You can do these arithmetic operations on matrices of different sizes, but only if one matrix has only one column or one row.**
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])