In [2]:
import numpy as np

In [3]:
# Array filled with zeros
np.zeros(2)

array([0., 0.])

In [5]:
# Arrays filled with ones
np.ones(2)

array([1., 1.])

In [7]:
# You can also create and "empty array"
np.empty(2)

#--Note :- a)the elements of this array are random----b)It is speedy over arrays of 1 or 0.
## REMEMBER TO FILL IT LATER##

array([1., 1.])

In [8]:
# Array using range
np.arange(4)



array([0, 1, 2, 3])

In [9]:
# Array of evenly spaced intervals
np.arange(2, 9, 2) #(first number, last number, the step size)

array([2, 4, 6, 8])

In [12]:
# Array with value linearly spaced
np.linspace(1, 10, num=5) #(first number, last number, num=intervals)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [17]:
#**Specify your dtype**
#default is np.float64
x = np.ones(2, dtype=np.int64) 
x.dtype

dtype('int64')

In [18]:
###--Adding removing and sorting elements-- ###

#np.sort()
#np.concatenate()

In [23]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

# np.argsort - which is an indirect sort along a specified axis
# np.lexsort -  which is an indirect stable sort on multiple keys,
# np.searchsorted - which will find elements in a sorted array, and
# np.partition - which is a partial sort.


array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
# You can concatenate them with np.concatenate().
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
# concatenate eg 2
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
###-- Reshaping a array --###

#arr.reshape()
#**The size of the original arrar == size of new array**

In [29]:
#create and array
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [31]:
#now reshape it
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [32]:
# How to convert a 1D array into a 2D array (how to add a new axis to an array)

# np.newaxis 
# np.expand_dims

In [33]:
# Example: If the start with array a
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [34]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [35]:
#you can convert a 1D array to a **row vector**:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [36]:
#for a **column vector**, you can insert an axis along the second dimension:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [37]:
#expand an array by inserting a new axis at a specified position with np.expand_dims.
#Example: if the start with a below
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [38]:
# add an axis at index position 1 with:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [39]:
# add an axis at index position 0 with:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [ ]:
###-- Advanced Indexing and slicing --###

In [43]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) #Example
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
#print all of the values in the array that are less than 5.
print(a[a < 5])

[1 2 3 4]


In [45]:
#equal to or greater than 5
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [46]:
#elements divisible by 2
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [ ]:
# Select elements using conditions & and | 
c = a[(a > 2) & (a < 11)]
print(c)

In [49]:
# Use & and | to return bool values
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [50]:
# Use np.nonzeros() to **select elements or indices**
# Example:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))
